alias: Volet
description: ""
trigger:
  - platform: sun
    event: sunrise
  - platform: sun
    event: sunset
  - platform: state
    entity_id:
      - sensor.xx_weather_alert
    attribute: Canicule
    enabled: true
  - platform: state
    entity_id:
      - input_select.mode_volet
    id: Mode
  - platform: state
    entity_id:
      - sensor.module_volet_cuisine_moving
      - sensor.module_volet_sejour_moving
      - sensor.module_volet_salon_moving
  - platform: numeric_state
    entity_id:
      - sensor.temp_maison
    above: 24
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Mode
            enabled: true
        sequence:
          - service: input_select.select_option
            data:
              option: "{{ states('input_select.mode_volet') }}"
            target:
              entity_id:
                - input_select.mode_voletouest
                - input_select.mode_voletsud
      - conditions:
          - condition: sun
            after: sunset
            before: sunrise
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_select.mode_volet
                    state: Ete
                  - condition: sun
                    after: sunset
                    after_offset: "00:00:00"
                sequence:
                  - service: cover.set_cover_position
                    data:
                      position: 20
                    target:
                      device_id:
                        - 1749e9c0cec4bfc8cadb6060b2109555
                        - be052f85354xx0b14a75e06914a6140d
                  - service: cover.set_cover_position
                    data:
                      position: 30
                    target:
                      device_id:
                        - 012fbd33f6b7cc0f9b5237f2a376a5a8
              - conditions:
                  - condition: not
                    conditions:
                      - condition: state
                        entity_id: input_select.mode_volet
                        state: Ete
                      - condition: state
                        entity_id: input_select.mode_volet
                        state: Manuel
                      - condition: state
                        entity_id: cover.volets_de_la_maison
                        state: closed
                  - condition: sun
                    after: sunset
                    after_offset: "00:00:00"
                sequence:
                  - service: cover.close_cover
                    data: {}
                    target:
                      entity_id:
                        - cover.volets_ouest
                        - cover.volets_sud
      - conditions:
          - condition: sun
            after: sunrise
            after_offset: "00:00:00"
            before: sunset
          - condition: not
            conditions:
              - condition: state
                state: "on"
                entity_id: binary_sensor.soleil_volets_ouest
              - condition: device
                device_id: 1749e9c0cec4bfc8cadb6060b2109555
                domain: cover
                entity_id: cover.module_volet_cuisine
                type: is_position
                above: 50
              - condition: device
                device_id: be052f85354xx0b14a75e06914a6140d
                domain: cover
                entity_id: cover.module_volet_sejour
                type: is_position
                above: 50
          - condition: state
            entity_id: input_select.mode_volet
            state: Ete
          - condition: state
            entity_id: sensor.xx_weather_alert
            attribute: Canicule
            state: Vert
            enabled: false
        sequence:
          - service: cover.set_cover_position
            data:
              position: 100
            target:
              entity_id: cover.volets_ouest
      - conditions:
          - condition: sun
            before: sunset
            after: sunrise
            after_offset: "00:00:00"
          - condition: not
            conditions:
              - condition: state
                entity_id: binary_sensor.soleil_volets_sud
                state: "on"
              - condition: device
                device_id: 012fbd33f6b7cc0f9b5237f2a376a5a8
                domain: cover
                entity_id: cover.module_volet_salon
                type: is_position
                above: 50
          - condition: and
            conditions:
              - condition: state
                entity_id: input_select.mode_volet
                state: Ete
              - condition: state
                entity_id: sensor.xx_weather_alert
                attribute: Canicule
                state: Vert
                enabled: false
        sequence:
          - service: cover.set_cover_position
            data:
              position: 100
            target:
              entity_id: cover.volets_sud
      - conditions:
          - condition: state
            entity_id: binary_sensor.soleil_volets_sud
            state: "on"
          - condition: and
            conditions:
              - condition: state
                entity_id: input_select.mode_volet
                state: Ete
              - condition: device
                device_id: 012fbd33f6b7cc0f9b5237f2a376a5a8
                domain: cover
                entity_id: cover.module_volet_salon
                type: is_position
                above: 50
        sequence:
          - service: cover.set_cover_position
            data:
              position: 35
            target:
              entity_id: cover.volets_sud
      - conditions:
          - condition: state
            entity_id: binary_sensor.soleil_volets_ouest
            state: "on"
          - condition: and
            conditions:
              - condition: state
                entity_id: input_select.mode_volet
                state: Ete
              - condition: device
                device_id: 1749e9c0cec4bfc8cadb6060b2109555
                domain: cover
                entity_id: cover.module_volet_cuisine
                type: is_position
                above: 50
              - condition: device
                device_id: be052f85354xx0b14a75e06914a6140d
                domain: cover
                entity_id: cover.module_volet_sejour
                type: is_position
                above: 50
        sequence:
          - service: cover.set_cover_position
            data:
              position: 35
            target:
              entity_id: cover.volets_ouest
      - conditions:
          - condition: state
            state: Normal
            entity_id: input_select.mode_volet
          - condition: sun
            before: sunset
            after: sunrise
          - condition: or
            conditions:
              - condition: state
                entity_id: group.all_covers_sud
                state: closed
              - condition: state
                entity_id: group.all_covers_ouest
                state: closed
            enabled: false
          - condition: or
            conditions:
              - condition: device
                device_id: 012fbd33f6b7cc0f9b5237f2a376a5a8
                domain: cover
                entity_id: cover.module_volet_salon
                type: is_closed
              - condition: device
                device_id: be052f85354xx0b14a75e06914a6140d
                domain: cover
                entity_id: cover.module_volet_sejour
                type: is_closed
        sequence:
          - service: cover.set_cover_position
            data:
              position: 100
            target:
              entity_id:
                - cover.volets_ouest
                - cover.volets_sud
      - conditions:
          - condition: sun
            before: sunset
            after: sunrise
          - condition: state
            state: Hiver
            entity_id: input_select.mode_volet
          - condition: or
            conditions:
              - condition: state
                entity_id: group.all_covers_ouest
                state: open
              - condition: state
                entity_id: group.all_covers_sud
                state: open
            enabled: false
        sequence:
          - service: cover.close_cover
            data: {}
            target:
              entity_id:
                - cover.volets_sud
                - cover.volets_ouest
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: sensor.xx_weather_alert
                attribute: Canicule
                state: Orange
              - condition: state
                entity_id: sensor.xx_weather_alert
                attribute: Canicule
                state: Rouge
              - condition: numeric_state
                entity_id: sensor.temp_maison
                above: 24
          - condition: not
            conditions:
              - condition: state
                entity_id: input_select.mode_volet
                state: Ete
        sequence:
          - service: notify.notify
            data:
              message: >-
                Alert Canicule :{% set weather_alert =
                state_attr('sensor.xx_weather_alert', 'Canicule') %} {% set
                message = '\U0001FA9F Volet mode Ete recommandé ' if
                weather_alert in ['Orange', 'Rouge'] else 'Fausse Alerte' %} {{
                message }}
    default: []
  - parallel:
      - if:
          - condition: or
            conditions:
              - condition: state
                entity_id: sensor.module_volet_salon_moving
                state: DOWN
              - condition: state
                entity_id: sensor.module_volet_salon_moving
                state: UP
        then:
          - delay:
              hours: 0
              minutes: 0
              seconds: 3
              milliseconds: 0
          - service: input_number.increment
            data: {}
            target:
              entity_id:
                - input_number.volet_salon_transitions
      - if:
          - condition: or
            conditions:
              - condition: state
                entity_id: sensor.module_volet_sejour_moving
                state: DOWN
              - condition: state
                entity_id: sensor.module_volet_sejour_moving
                state: UP
        then:
          - delay:
              hours: 0
              minutes: 0
              seconds: 3
              milliseconds: 0
          - service: input_number.increment
            data: {}
            target:
              entity_id:
                - input_number.volet_sejour_transitions
      - if:
          - condition: or
            conditions:
              - condition: state
                entity_id: sensor.module_volet_cuisine_moving
                state: DOWN
              - condition: state
                entity_id: sensor.module_volet_cuisine_moving
                state: UP
        then:
          - delay:
              hours: 0
              minutes: 0
              seconds: 3
              milliseconds: 0
          - service: input_number.increment
            data: {}
            target:
              entity_id:
                - input_number.volet_cuisine_transitions
      - if:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: input_number.volet_cuisine_transitions
                above: 5
              - condition: numeric_state
                entity_id: input_number.volet_salon_transitions
                above: 5
              - condition: numeric_state
                entity_id: input_number.volet_sejour_transitions
                above: 5
          - condition: template
            value_template: >-
              {{ (now() -
              states.cover.volets_de_la_maison.last_changed).total_seconds() /
              60 < 30 }}
        then:
          - service: notify.notify
            data:
              message: ⚠️ Risque de surchauffe du moteur des volets
        else:
          - service: input_number.set_value
            data:
              value: 0
            target:
              entity_id:
                - input_number.volet_salon_transitions
                - input_number.volet_cuisine_transitions
                - input_number.volet_sejour_transitions
mode: restart
